### PR TITLE
Added missing vars to wordpress.config

### PR DESCRIPTION
**Pull request by jribe**
These variables are used in wp-config.php, but aren't included in this convenience list.

### CODE REVIEW

**Comment by mwunderl** [comment]
We should add LOGGED_IN_SALT, but what's the point of adding the database variables?

**Comment by jribe** [comment]
Convenience. Having all the variables added by default makes it easier to go through the setup process.

**Comment by mwunderl** [comment]
Can you tell me how? For both sets of instructions, the environment variables should be configured before you install WP.
Thanks,
-Michael

**Comment by jribe** [comment]
The instructions I used (http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/php-hawordpress-tutorial.html) tell you to create the EB environment first, then configure the environment variables.

When using that workflow, these default values are already populated in the EB management UI when you go to configure the environment variables. In the current state, a subset of variables are populated this way, so the user needs to double-check and cross-reference the documentation in order to make sure that they've added all of the variables.

**Comment by mwunderl** [comment]
Makes perfect sense. Thank you!

**Pull request merged**
